name=DynamixelARCoS
version=1.0.0
author=Muhammad Lutfi Nur Anendi
maintainer=Muhammad Lutfi Nur Anendi 
sentence=Half-duplex Dynamixel AX-12A/AX-18A driver for ESP32/Arduino with control pin.
paragraph=Simple low-level driver for Dynamixel AX series using ESP32 hardware serial and half-duplex line control (74HC241).
category=Device Control
url=https://github.com/lutfiianendi/DynamixelARCoS.com
architectures=avr,esp8266,esp32
